/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sample_Sample */

#ifndef _Included_sample_Sample
#define _Included_sample_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sample_Sample
 * Method:    voidFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sample_Sample_voidFunc
  (JNIEnv *, jobject);

/*
 * Class:     sample_Sample
 * Method:    voidFuncl
 * Signature: (JCZBSIFDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_sample_Sample_voidFuncl
  (JNIEnv *, jobject, jlong, jchar, jboolean, jbyte, jshort, jint, jfloat, jdouble, jstring);

/*
 * Class:     sample_Sample
 * Method:    voidFuncp
 * Signature: (Lsample/Sample;)V
 */
JNIEXPORT void JNICALL Java_sample_Sample_voidFuncp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     sample_Sample
 * Method:    intFunc
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sample_Sample_intFunc
  (JNIEnv *, jobject);

/*
 * Class:     sample_Sample
 * Method:    intFunci
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_sample_Sample_intFunci
  (JNIEnv *, jobject, jint);

/*
 * Class:     sample_Sample
 * Method:    floatFuncf
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_sample_Sample_floatFuncf
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     sample_Sample
 * Method:    doubleFuncd
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_sample_Sample_doubleFuncd
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     sample_Sample
 * Method:    doubleFuncdd
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_sample_Sample_doubleFuncdd
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
