enum SampleEnum {
	"SE_0",
	"SE_1",
	"SE_2"
};

interface SampleA {
  attribute float a;
  attribute SampleEnum et;
  void SampleA();
  void print();
  SampleEnum getEnum(SampleEnum p);
};

[Internal="SampleBStruct"]
interface SampleB {
attribute double b;

[CObject,Internal="SampleBStruct_print"] void print();
};

interface Sample {
attribute long x;
attribute long y;
	void Sample();
 	int funci(int x);
	void print();
  SampleA makeA();
	void gatherPtr(float *array, int num);
	void gatherArray(float []array, int num);
	
//  SampleB makeB();

// 	[Operator="*",Ref] Sample op_add( [Const,Ref] Sample p );
 	double length();
};

