interface SampleA {
  attribute float a;
  void SampleA();
  void print();
};

[Internal="SampleBStruct"]
interface SampleB {
attribute double b;

[CObject,Internal="SampleBStruct_print"] void print();
};

interface Sample {
attribute long x;
attribute long y;
	void Sample();
 	int funci(int x);
	void print();
  SampleA makeA();
//  SampleB makeB();

// 	[Operator="*",Ref] Sample op_add( [Const,Ref] Sample p );
 	double length();
};

